# Generated by Django 3.1.7 on 2021-04-04 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator('5')])),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=4096)),
            ],
        ),
    ]
